/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java

    application

    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

javafx {
    version = "21"
    modules = listOf("javafx.controls", "javafx.fxml")
}

dependencies {
    // Database (Hibernate (JPA) & MySQL)

    // Hibernate Core
    // Bring in all the JPA interfaces
    implementation("org.hibernate:hibernate-core:5.6.15.Final")

    implementation("io.github.mkpaz:atlantafx-base:2.0.1")

    // --- Security ---
    // For hashing passwords (BCrypt)
    implementation("org.springframework.security:spring-security-crypto:6.1.5")
    implementation("commons-logging:commons-logging:1.2")

    // MySQL Connector
    // Hibernate - MySQL driver
    implementation("mysql:mysql-connector-java:8.0.33")

    // Tests
    testImplementation(platform("org.junit:junit-bom:5.9.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

application {
    mainClass.set("com.bankapp.MainApp")
}

tasks.test {
    useJUnitPlatform()
}
